#!/usr/bin/env python3
"""
Tests for core functionality
"""

import pytest
import tempfile
import os
import yaml
from pathlib import Path
from err_x509.core import X509Fixer


@pytest.fixture
def fixer():
    return X509Fixer()


@pytest.fixture
def single_line_config():
    return """port: 7890 proxies: - {name: test1, server: s1.com} - {name: test2, server: s2.com}"""


@pytest.fixture
def multi_line_config():
    return """port: 7890
proxies:
  - name: test1
    server: s1.com
  - name: test2
    server: s2.com"""


@pytest.fixture
def config_with_ssl():
    return """port: 7890
proxies:
  - {name: test1, server: s1.com, skip-cert-verify: false}
  - {name: test2, server: s2.com, skip-cert-verify: true}"""


class TestX509Fixer:
    def test_normalize_config_single_line(self, fixer, single_line_config):
        normalized = fixer.normalize_config(single_line_config)
        assert "proxies:" in normalized
        assert "\n" in normalized
        assert "  -" in normalized

    def test_normalize_config_multi_line(self, fixer, multi_line_config):
        normalized = fixer.normalize_config(multi_line_config)
        assert "proxies:" in normalized
        assert "  - name:" in normalized

    def test_process_proxy(self, fixer):
        proxy = {"name": "test", "server": "example.com", "port": 443}
        processed = fixer.process_proxy(proxy)

        assert "skip-cert-verify" in processed
        assert processed["skip-cert-verify"] is True
        assert fixer.proxy_count == 1

    def test_fix_with_yaml(self, fixer, multi_line_config):
        fixed, count = fixer.fix_with_yaml(multi_line_config)

        assert "skip-cert-verify: true" in fixed
        assert count == 2

        # Verify YAML is valid
        data = yaml.safe_load(fixed)
        assert "proxies" in data
        assert len(data["proxies"]) == 2
        assert all(p["skip-cert-verify"] for p in data["proxies"])

    def test_fix_with_yaml_updates_existing(self, fixer, config_with_ssl):
        fixed, count = fixer.fix_with_yaml(config_with_ssl)

        data = yaml.safe_load(fixed)
        assert all(p["skip-cert-verify"] for p in data["proxies"])
        assert count == 2

    def test_fix_manually(self, fixer, single_line_config):
        fixed, count = fixer.fix_manually(single_line_config)

        assert "skip-cert-verify: true" in fixed
        assert count == 2

    def test_fix_file_success(self, fixer, multi_line_config):
        with tempfile.NamedTemporaryFile(mode="w", suffix=".yaml", delete=False) as f:
            f.write(multi_line_config)
            input_file = f.name

        try:
            success, output_file, count = fixer.fix_file(input_file)

            assert success is True
            assert os.path.exists(output_file)
            assert count == 2

            # Verify output file
            with open(output_file, "r") as f:
                content = f.read()
                assert "skip-cert-verify: true" in content

        finally:
            # Cleanup
            for file in [input_file, output_file]:
                if file and os.path.exists(file):
                    os.unlink(file)

    def test_fix_file_not_found(self, fixer):
        success, output_file, count = fixer.fix_file("nonexistent.yaml")
        assert success is False
        assert output_file == ""
        assert count == 0

    def test_fix_directory(self, fixer, tmp_path):
        # Create test files
        config1 = tmp_path / "config1.yaml"
        config2 = tmp_path / "config2.yaml"

        config1.write_text(
            """port: 7890
proxies:
  - {name: test1, server: s1.com}"""
        )

        config2.write_text(
            """port: 7890
proxies:
  - {name: test2, server: s2.com}
  - {name: test3, server: s3.com}"""
        )

        # Fix directory
        results = fixer.fix_directory(str(tmp_path))

        assert len(results) == 2
        assert all(success for success, _, _ in results.values())

        # Check output files exist
        for input_file, (success, output_file, count) in results.items():
            assert Path(output_file).exists()
            assert count > 0

    def test_add_metadata(self, fixer, multi_line_config):
        input_file = "test.yaml"
        output_file = "test_fixed.yaml"

        result = fixer.add_metadata(multi_line_config, input_file, output_file)

        assert "# Generated by err_x509" in result
        assert "Statistics" in result
        assert input_file in result
        assert output_file in result


class TestBackup:
    def test_create_backup(self, fixer, tmp_path):
        test_file = tmp_path / "test.yaml"
        test_file.write_text("test content")

        backup_path = fixer.create_backup(str(test_file))

        assert backup_path is None  # backup=False by default

    def test_create_backup_with_backup_enabled(self, tmp_path):
        fixer = X509Fixer(backup=True)
        test_file = tmp_path / "test.yaml"
        test_file.write_text("test content")

        backup_path = fixer.create_backup(str(test_file))

        assert backup_path is not None
        assert Path(backup_path).exists()
        assert Path(backup_path).read_text() == "test content"


class TestErrorHandling:
    def test_invalid_yaml(self, fixer):
        invalid_yaml = "port: 7890\ninvalid: [unclosed list"

        with pytest.raises(Exception):
            fixer.fix_with_yaml(invalid_yaml)

    def test_empty_file(self, fixer, tmp_path):
        empty_file = tmp_path / "empty.yaml"
        empty_file.write_text("")

        success, output_file, count = fixer.fix_file(str(empty_file))

        # Should succeed but process 0 proxies
        assert success is True
        assert count == 0
